name: Dependency check

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 2 * * 5'

jobs:
  python-check:
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Verify Python version
        run: python --version

      - name: Install library
        run: pip install -e .
