name: Dependency check

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 2 * * *'

jobs:
  python-latest:
    runs-on: ubuntu-latest
    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v2

      - name: install lib
        run: pip install -e .

  minimum-python37:
    runs-on: ubuntu-latest
    container:
      image: python:3.7

    steps:
      - uses: actions/checkout@v2

      - name: install lib
        run: pip install -e .
